# Helix Configuration
theme = "github_dark"

[editor]
end-of-line-diagnostics = "hint"
line-number = "relative"
cursorline = true
mouse = true
auto-format = true
true-color = true

# Essential for quick edits & nano-users transitioning over:
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true # Shows hidden dotfiles (critical when editing ~/.config files!)

[editor.whitespace.render]
space = "all"
tab = "all"

# Quick buffer navigation (Neovim style)
[keys.normal]
"L" = ":buffer-next"
"H" = ":buffer-previous"
"Q" = ":buffer-close"