name: Auto Deploy Nix Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run install script
        run: |
          chmod +x ./install.sh
          ./install.sh update